/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista.docente;

import controlador.TDA.listas.Exception.EmptyException;
import controlador.clases.AsistenciaControl;
import controlador.clases.EstudianteControl;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modelo.Estudiante;
import modelo.Horario;
import vista.modeloTablas.ModeloTablaAsistencia;
import vista.utiles.UtilVista;

/**
 *
 * @author Usuario iTC
 */
public class frmAsistencia extends javax.swing.JFrame {
        
        private ModeloTablaAsistencia mta = new ModeloTablaAsistencia();
        private EstudianteControl controlE = new EstudianteControl();
        private AsistenciaControl controlAsis = new AsistenciaControl();
        
        private void cargarCombo() {
                try {
                        UtilVista.cargarcomboBoxCursa(cbxCurso);
                        UtilVista.cargarcomboBoxEstadoAsistencia(cbxEstadoAsistencia);
                        UtilVista.cargarcomboBoxHorario(cbxHorario);
                        cbxEstadoAsistencia.setEnabled(false);
                        cbxHorario.setEnabled(false);
                } catch (Exception e) {
                }
        }
        
        private void cargarTabla() {
                tblLista.setModel(mta);
                tblLista.updateUI();
                tblLista.setEnabled(false);
        }
        
        private void seleccionarMateria() {
                cbxHorario.setEnabled(true);
                cbxMateria.setEnabled(true);
                cbxCurso.setEnabled(false);
                cbxEstadoAsistencia.setEnabled(true);
                try {
                        UtilVista.cargarcomboBoxAsignatura(cbxMateria);
                } catch (Exception e) {
                }
        }
        
        private void Asignar() {
                mta.setEstudiantes(controlE.getListaEstudiantes());
                tblLista.setModel(mta);
                tblLista.updateUI();
        }
        
        private void guardar() throws EmptyException {
                for (int i = 0; i < tblLista.getSelectedRowCount(); i++) {
                        Estudiante aux = controlE.getListaEstudiantes().getInfo(i);
//                        controlAsis.getAsistencia().setEstudiante(aux);
//                        String texto = String.valueOf(cbxEstadoAsistencia.getSelectedItem());
//                        controlAsis.getAsistencia().getEstadoAsistencia().setNombre(texto);
//                        controlAsis.getAsistencia().getClaseDictada().setTema(txtTema.getText().trim());
//                        controlAsis.getAsistencia().setHorario((Horario) cbxHorario.getSelectedItem());
//                        controlAsis.getAsistencia().setFecha(txtFecha.getDate());
//                        controlAsis.getAsistencia().getHorario().setFecha(txtFecha.getDate());
                        if (controlAsis.persist()) {
                                JOptionPane.showMessageDialog(null, "Guardado Exitoso");
                        } else {
                                JOptionPane.showMessageDialog(null, "No se pudo guardar");
                        }
                        controlAsis.setAsistencia(null);
                }
        }

        /*if (verificar()) {
            docenteControl.getDocente().setNombre(txtNombre.getText());
            docenteControl.getDocente().setApellido(txtApellido.getText());
            docenteControl.getDocente().setDni(txtDni.getText());
            docenteControl.getDocente().setTitulo(txtTitulo.getText());

            if (docenteControl.persist()) {
                JOptionPane.showMessageDialog(null, "Guardado Exitoso");
            } else {
                JOptionPane.showMessageDialog(null, "No se pudo guardar");
            }
            docenteControl.setDocente(null);
            limpiar();
        }*/
        /**
         * Creates new form frmAsistencia
         */
        public frmAsistencia() throws EmptyException {
                initComponents();
                cargarCombo();
        }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                cbxMateria = new javax.swing.JComboBox<>();
                cbxCurso = new javax.swing.JComboBox<>();
                btnBuscar = new javax.swing.JButton();
                jLabel1 = new javax.swing.JLabel();
                btnGuardar = new javax.swing.JButton();
                jLabel3 = new javax.swing.JLabel();
                jLabel4 = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                jLabel5 = new javax.swing.JLabel();
                jPanel2 = new javax.swing.JPanel();
                HEADER = new javax.swing.JLabel();
                jLabel6 = new javax.swing.JLabel();
                txtFecha = new com.toedter.calendar.JDateChooser();
                jScrollPane1 = new javax.swing.JScrollPane();
                tblLista = new javax.swing.JTable();
                btnAsignar = new javax.swing.JButton();
                jLabel7 = new javax.swing.JLabel();
                txtTema = new javax.swing.JTextField();
                cbxHorario = new javax.swing.JComboBox<>();
                jLabel8 = new javax.swing.JLabel();
                cbxEstadoAsistencia = new javax.swing.JComboBox<>();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                jPanel1.setBackground(new java.awt.Color(255, 255, 255));
                jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                cbxMateria.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
                cbxMateria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Seleccione una Materia--", "Estructura de Datos", "Arquitectura de Ordenadores", "Base de Datos" }));
                cbxMateria.setEnabled(false);
                jPanel1.add(cbxMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 180, -1));

                cbxCurso.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
                cbxCurso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Seleccione un Curso--", "3ro A", "3ro B", "2do A", "1ro A" }));
                jPanel1.add(cbxCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

                btnBuscar.setBackground(new java.awt.Color(255, 255, 255));
                btnBuscar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
                btnBuscar.setText("Buscar");
                btnBuscar.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnBuscarActionPerformed(evt);
                        }
                });
                jPanel1.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 69, -1));

                jLabel1.setBackground(new java.awt.Color(0, 0, 0));
                jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
                jLabel1.setText("Horario:");
                jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));

                btnGuardar.setBackground(new java.awt.Color(255, 255, 255));
                btnGuardar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
                btnGuardar.setText("Guardar");
                btnGuardar.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnGuardarActionPerformed(evt);
                        }
                });
                jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 550, 73, -1));

                jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
                jLabel3.setText("Estado:");
                jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, -1, -1));

                jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
                jLabel4.setText("Curso:");
                jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

                jLabel2.setBackground(new java.awt.Color(255, 255, 255));
                jLabel2.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
                jLabel2.setForeground(new java.awt.Color(255, 255, 255));
                jLabel2.setText("ASISTENCIAS");
                jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, -1, -1));

                jLabel5.setBackground(new java.awt.Color(255, 255, 255));
                jLabel5.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
                jLabel5.setForeground(new java.awt.Color(255, 255, 255));
                jLabel5.setText("ASIGNACIÓN DE");
                jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, -1, -1));

                jPanel2.setBackground(new java.awt.Color(0, 0, 0));

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 800, Short.MAX_VALUE)
                );
                jPanel2Layout.setVerticalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 10, Short.MAX_VALUE)
                );

                jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 800, 10));

                HEADER.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/recursos/HEADER.jpg"))); // NOI18N
                HEADER.setText("jLabel7");
                HEADER.setAutoscrolls(true);
                HEADER.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                jPanel1.add(HEADER, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 800, 170));

                jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
                jLabel6.setText("Tema:");
                jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));
                jPanel1.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 100, -1));

                tblLista.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {

                        },
                        new String [] {
                                "null"
                        }
                ) {
                        Class[] types = new Class [] {
                                java.lang.String.class
                        };

                        public Class getColumnClass(int columnIndex) {
                                return types [columnIndex];
                        }
                });
                tblLista.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                tblListaMouseClicked(evt);
                        }
                });
                jScrollPane1.setViewportView(tblLista);

                jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 181, 530, 350));

                btnAsignar.setBackground(new java.awt.Color(255, 255, 255));
                btnAsignar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
                btnAsignar.setText("Asignar");
                btnAsignar.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnAsignarActionPerformed(evt);
                        }
                });
                jPanel1.add(btnAsignar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 73, -1));

                jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
                jLabel7.setText("Materia:");
                jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));
                jPanel1.add(txtTema, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 240, -1));

                cbxHorario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
                jPanel1.add(cbxHorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 100, -1));

                jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
                jLabel8.setText("Fecha:");
                jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, -1));

                cbxEstadoAsistencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
                jPanel1.add(cbxEstadoAsistencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, 100, -1));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE)
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
                seleccionarMateria();
        }//GEN-LAST:event_btnBuscarActionPerformed

        private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
                try {
                        guardar();
                        
                } catch (EmptyException ex) {
                        Logger.getLogger(frmAsistencia.class
                                .getName()).log(Level.SEVERE, null, ex);
                }
        }//GEN-LAST:event_btnGuardarActionPerformed

        private void tblListaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblListaMouseClicked

        }//GEN-LAST:event_tblListaMouseClicked

        private void btnAsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarActionPerformed
                Asignar();
        }//GEN-LAST:event_btnAsignarActionPerformed

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
                /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                        
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(frmAsistencia.class
                                .getName()).log(java.util.logging.Level.SEVERE, null, ex);
                        
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(frmAsistencia.class
                                .getName()).log(java.util.logging.Level.SEVERE, null, ex);
                        
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(frmAsistencia.class
                                .getName()).log(java.util.logging.Level.SEVERE, null, ex);
                        
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(frmAsistencia.class
                                .getName()).log(java.util.logging.Level.SEVERE, null, ex);
                }
                //</editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                try {
                                        new frmAsistencia().setVisible(true);
                                        
                                } catch (EmptyException ex) {
                                        Logger.getLogger(frmAsistencia.class
                                                .getName()).log(Level.SEVERE, null, ex);
                                }
                        }
                });
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JLabel HEADER;
        private javax.swing.JButton btnAsignar;
        private javax.swing.JButton btnBuscar;
        private javax.swing.JButton btnGuardar;
        private javax.swing.JComboBox<String> cbxCurso;
        private javax.swing.JComboBox<String> cbxEstadoAsistencia;
        private javax.swing.JComboBox<String> cbxHorario;
        private javax.swing.JComboBox<String> cbxMateria;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JLabel jLabel8;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JTable tblLista;
        private com.toedter.calendar.JDateChooser txtFecha;
        private javax.swing.JTextField txtTema;
        // End of variables declaration//GEN-END:variables
}
