/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista.estudiante;

import controlador.TDA.listas.Exception.EmptyException;
import controlador.clases.AsistenciaControl;
import controlador.clases.EstudianteControl;
import java.util.logging.Level;
import java.util.logging.Logger;
import vista.modeloTablas.ModeloTablaVerAsistencia;

/**
 *
 * @author Usuario iTC
 */
public class frmEstudiante extends javax.swing.JFrame {
        
        private ModeloTablaVerAsistencia mtva = new ModeloTablaVerAsistencia();
        private EstudianteControl controlE = new EstudianteControl();
        private AsistenciaControl controlAsis = new AsistenciaControl();
        
        
        private void cargarTabla() {
                tblAsistencia.setModel(mtva);
                tblAsistencia.updateUI();
                tblAsistencia.setEnabled(false);
        }
        
        private void cargarTablaVista() {
                mtva.setAsistencias(controlAsis.getListaEstadoAsistencia());
                mtva.setEstudiantes(controlE.getListaEstudiantes());
                tblAsistencia.setModel(mtva);
                tblAsistencia.updateUI();
        }
        
        public frmEstudiante() throws EmptyException {
                initComponents();
                cargarTabla();
        }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                btnBuscar = new javax.swing.JButton();
                jLabel2 = new javax.swing.JLabel();
                jLabel5 = new javax.swing.JLabel();
                jPanel2 = new javax.swing.JPanel();
                HEADER = new javax.swing.JLabel();
                jScrollPane1 = new javax.swing.JScrollPane();
                tblAsistencia = new javax.swing.JTable();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                jPanel1.setBackground(new java.awt.Color(255, 255, 255));
                jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                btnBuscar.setBackground(new java.awt.Color(255, 255, 255));
                btnBuscar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
                btnBuscar.setText("Buscar");
                btnBuscar.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnBuscarActionPerformed(evt);
                        }
                });
                jPanel1.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 550, 69, -1));

                jLabel2.setBackground(new java.awt.Color(255, 255, 255));
                jLabel2.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
                jLabel2.setForeground(new java.awt.Color(255, 255, 255));
                jLabel2.setText("ASISTENCIAS");
                jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, -1, -1));

                jLabel5.setBackground(new java.awt.Color(255, 255, 255));
                jLabel5.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
                jLabel5.setForeground(new java.awt.Color(255, 255, 255));
                jLabel5.setText("VISTA DE ");
                jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, -1, -1));

                jPanel2.setBackground(new java.awt.Color(0, 0, 0));

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 800, Short.MAX_VALUE)
                );
                jPanel2Layout.setVerticalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 10, Short.MAX_VALUE)
                );

                jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 800, 10));

                HEADER.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/recursos/HEADER.jpg"))); // NOI18N
                HEADER.setText("jLabel7");
                HEADER.setAutoscrolls(true);
                HEADER.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                jPanel1.add(HEADER, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 800, 170));

                tblAsistencia.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {

                        },
                        new String [] {
                                "null"
                        }
                ) {
                        Class[] types = new Class [] {
                                java.lang.String.class
                        };

                        public Class getColumnClass(int columnIndex) {
                                return types [columnIndex];
                        }
                });
                tblAsistencia.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                tblAsistenciaMouseClicked(evt);
                        }
                });
                jScrollPane1.setViewportView(tblAsistencia);

                jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 181, 780, 350));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE)
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
                cargarTablaVista();
        }//GEN-LAST:event_btnBuscarActionPerformed

        private void tblAsistenciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAsistenciaMouseClicked

        }//GEN-LAST:event_tblAsistenciaMouseClicked

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
                /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                        
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(frmEstudiante.class
                                .getName()).log(java.util.logging.Level.SEVERE, null, ex);
                        
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(frmEstudiante.class
                                .getName()).log(java.util.logging.Level.SEVERE, null, ex);
                        
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(frmEstudiante.class
                                .getName()).log(java.util.logging.Level.SEVERE, null, ex);
                        
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(frmEstudiante.class
                                .getName()).log(java.util.logging.Level.SEVERE, null, ex);
                }
                //</editor-fold>
                //</editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                try {
                                        new frmEstudiante().setVisible(true);
                                        
                                } catch (EmptyException ex) {
                                        Logger.getLogger(frmEstudiante.class
                                                .getName()).log(Level.SEVERE, null, ex);
                                }
                        }
                });
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JLabel HEADER;
        private javax.swing.JButton btnBuscar;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JTable tblAsistencia;
        // End of variables declaration//GEN-END:variables
}
